pygments: true
permalink: none
paginate: 3
baseurl: /0pointer
siteurl: http://www.marianosimone.com.ar

# Custom conf
name: 0pointer
tagline: pointing nowhere
personalurl: http://www.marianosimone.com.ar

